DROP TABLE IF EXISTS status_histories;
DROP TABLE IF EXISTS loan_transactions;
DROP TABLE IF EXISTS repayment_schedules;
DROP TABLE IF EXISTS loan_contracts;
DROP TABLE IF EXISTS credit_assessments;
DROP TABLE IF EXISTS loan_applications;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_no VARCHAR(20) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(200),
    phone VARCHAR(20),
    annual_income NUMERIC(15, 2),
    employment_type VARCHAR(30),
    company VARCHAR(200),
    birth_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_no VARCHAR(20) UNIQUE NOT NULL,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    requested_amount NUMERIC(15, 2) NOT NULL,
    requested_term_months INT NOT NULL,
    repayment_method VARCHAR(50) NOT NULL,
    existing_loan_amount NUMERIC(15, 2) DEFAULT 0,
    purpose VARCHAR(4000),
    status VARCHAR(20) NOT NULL,
    applied_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE credit_assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES loan_applications(id) UNIQUE,
    credit_score INT,
    credit_grade VARCHAR(20),
    dsr_ratio NUMERIC(5, 2),
    approved_rate NUMERIC(5, 2),
    approved_amount NUMERIC(15, 2),
    approved_term_months INT,
    result VARCHAR(20) NOT NULL,
    rejection_reason VARCHAR(4000),
    assessed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_no VARCHAR(20) UNIQUE NOT NULL,
    application_id BIGINT NOT NULL REFERENCES loan_applications(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    principal_amount NUMERIC(15, 2) NOT NULL,
    interest_rate NUMERIC(5, 2) NOT NULL,
    term_months INT NOT NULL,
    repayment_method VARCHAR(50) NOT NULL,
    monthly_payment NUMERIC(15, 2) NOT NULL,
    outstanding_balance NUMERIC(15, 2) NOT NULL,
    total_interest_paid NUMERIC(15, 2) DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    start_date DATE,
    end_date DATE,
    executed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE repayment_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES loan_contracts(id),
    installment_no INT NOT NULL,
    due_date DATE NOT NULL,
    principal_amount NUMERIC(15, 2) NOT NULL,
    interest_amount NUMERIC(15, 2) NOT NULL,
    total_amount NUMERIC(15, 2) NOT NULL,
    outstanding_balance_after NUMERIC(15, 2) NOT NULL,
    status VARCHAR(20) DEFAULT 'SCHEDULED',
    paid_date DATE,
    paid_amount NUMERIC(15, 2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE loan_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_no VARCHAR(30) UNIQUE NOT NULL,
    contract_id BIGINT NOT NULL REFERENCES loan_contracts(id),
    type VARCHAR(30) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    balance_after NUMERIC(15, 2) NOT NULL,
    description VARCHAR(4000),
    transacted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE status_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    from_status VARCHAR(20),
    to_status VARCHAR(20) NOT NULL,
    changed_by VARCHAR(100),
    reason VARCHAR(4000),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
